# Generated by Django 2.0.13 on 2019-03-23 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lampada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.DecimalField(decimal_places=1, max_digits=20)),
                ('ping', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Funcionando', 'Funcionando'), ('Lâmpada Queimada', 'Lâmpada Queimada'), ('Sistema indisponível', 'Sistema Indisponível')], max_length=30)),
                ('intensity', models.CharField(choices=[('100%', '100%'), ('30%', '30%')], max_length=30)),
            ],
        ),
    ]
