# Generated by Django 2.0.13 on 2019-03-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampada',
            name='intensity',
            field=models.PositiveSmallIntegerField(max_length=100),
        ),
    ]
