# Generated by Django 2.0.13 on 2019-03-30 21:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lampada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('working', 'Funcionando'), ('broken', 'Lâmpada Queimada'), ('unavailable', 'Sistema Indisponível')], max_length=30)),
                ('intensity', models.PositiveSmallIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('last_ping', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'lâmpada',
                'verbose_name_plural': 'lâmpadas',
            },
        ),
    ]
