# Generated by Django 2.0.13 on 2019-03-30 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lampada',
            options={'ordering': ['id'], 'verbose_name': 'lâmpada', 'verbose_name_plural': 'lâmpadas'},
        ),
    ]
